version: '3.9'

services:
  cinema_db:
    container_name: cinema_db
    image: postgres:12.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  cinema:
    container_name: cinema
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - cinema_db

volumes:
  postgres_data: