# Generated by Django 4.0.6 on 2022-07-06 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0003_alter_seat_room"),
        ("movie", "0004_showtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showtime",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="showtime",
                to="cinema.room",
            ),
        ),
    ]
