# Generated by Django 4.0.6 on 2022-07-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_total_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="order.order",
            ),
        ),
    ]
