# Generated by Django 4.0.6 on 2022-07-13 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_ticket_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
